HW3 is completed
aik27/otus_go_home_work pull request #3
Opened 2024-12-08 04:11 UTC by aik27

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-12-16 15:11 UTC, agneum requested changes

2024-12-16 15:11 UTC, agneum commented on hw03_frequency_analysis/top_test.go
> +var taskWithAsteriskIsCompleted = true
Не хватает новых юнит-тестов

2024-12-17 05:58 UTC, aik27 commented on hw03_frequency_analysis/top_test.go
> +var taskWithAsteriskIsCompleted = true
Добавил

2024-12-17 08:40 UTC, agneum approved these changes
Спасибо за вариант решения. Хорошая работа
Итого: 8 баллов из 10. Принято

2024-12-17 08:40 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	}
Не понимаю, почему именно эта строка возвращается в неизменном виде

2024-12-17 08:40 UTC, agneum commented on hw03_frequency_analysis/top.go
> +		existWord := findWordByStr(val, words)
Похоже, у алгоритма квадратичная сложность.
Рекомендовал бы использовать мапу для подсчёта повторяющихся слов

2024-12-24 11:20 UTC, aik27 commented on hw03_frequency_analysis/top.go
> +	}
Заменил на регулярное выражение

2024-12-24 11:20 UTC, aik27 commented on hw03_frequency_analysis/top.go
> +		existWord := findWordByStr(val, words)
Переделал на мапу

2024-12-25 08:51 UTC, agneum approved these changes

2024-12-25 08:51 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	result := make([]string, 0, len(strSpt))
Эти слайсы будут содержать гораздо меньше слов, чем в `strSpt`. 
Не рекомендовал бы аллоцировать их такой большой размерности

2024-12-25 08:51 UTC, agneum commented on hw03_frequency_analysis/top.go
> +		}
Можно не проверять наличие слова и сразу делать инкремент

2024-12-25 08:51 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	})
Кажется, что эта сортировка необязательна, потому что sort.Slice отсортирует элементы сразу по двум полям

2024-12-26 12:40 UTC, aik27 commented on hw03_frequency_analysis/top.go
> +	result := make([]string, 0, len(strSpt))
Поправил

2024-12-26 12:40 UTC, aik27 commented on hw03_frequency_analysis/top.go
> +		}
Поправил

2024-12-26 12:40 UTC, aik27 commented on hw03_frequency_analysis/top.go
> +	})
Поправил

2024-12-28 14:03 UTC, agneum approved these changes

2025-01-02 13:02 UTC, merged